/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 10.4.21-MariaDB : Database - ulio
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ulio` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `ulio`;

/*Table structure for table `about` */

DROP TABLE IF EXISTS `about`;

CREATE TABLE `about` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `about` */

insert  into `about`(`id`,`title`,`image`,`description`,`slug`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'beatae ut','1654587132.jpg','Ipsam eaque et eum tempore cum. Molestias soluta soluta ipsa consequatur. Sint enim quis et magni qui deserunt doloremque. Magnam consectetur non fugit et sit. Aliquid recusandae aliquid cumque quidem aut. Distinctio quaerat nihil adipisci error qui nam repellendus. Qui exercitationem ab corporis fugit fugiat incidunt labore. Quis qui dolores ea numquam porro sed neque. Alias commodi esse quam et qui et. Consectetur et non quam dolorem. Temporibus totam ut alias. Ipsam explicabo enim explicabo deserunt animi odit. Quis assumenda excepturi et est consequatur nulla. Aut voluptas rerum quibusdam reprehenderit. Officia ab consequatur et vel dolores et neque. Aspernatur et eaque sunt est quidem est eveniet aut. Perspiciatis rerum consequatur dolor modi ullam. Qui unde id architecto. Et voluptas delectus dolorem. Accusamus rerum rerum perspiciatis reprehenderit officiis rem minima. Dolorum fugit nihil harum. Explicabo illo repudiandae ea perferendis libero repellendus eligendi. Perspiciatis temporibus ea enim. Itaque consequatur reiciendis nam est praesentium repudiandae. Architecto ut quis ut velit consectetur. Voluptates aut perspiciatis omnis cum et optio quo ut. Velit eos rerum corrupti laboriosam possimus vel. Porro quia commodi qui animi voluptas. Sint nihil sed dolor sunt alias. Repellendus consequuntur dignissimos consequatur porro maiores ratione.','temporibus-maiores-est','2022-06-07 07:29:25','2022-06-07 07:32:12',NULL),
(2,'explicabo velit','1654587132.jpg','Sit assumenda rerum quam temporibus quis odio. Magnam aut velit quidem dolores. Repellendus eos voluptatibus accusamus aliquam autem qui voluptas tempora. Vel officiis qui in illo vel occaecati. Aperiam nesciunt numquam aperiam at. Voluptates natus in voluptatem enim perspiciatis consectetur repellat. Similique ratione aliquam qui ea nobis corrupti unde. Modi impedit unde dolorem est et sint adipisci. Maxime dignissimos quia blanditiis fugiat quae molestiae. Dolores nostrum assumenda tempore culpa. Officiis ullam aspernatur quos qui qui hic. Nulla voluptate quis eveniet voluptates aperiam praesentium ab. Accusantium voluptatem ratione qui qui ex et. Nisi beatae incidunt enim. Officia voluptatem eos aut sit accusamus vitae illo. Error nisi explicabo accusamus provident non nam occaecati. Recusandae voluptates eveniet accusantium dolorum quasi laborum necessitatibus magnam. Ut expedita harum cum dolorem error veniam eos. Fuga incidunt doloribus perspiciatis molestias vero nulla. Provident sit et dolor quae illum. Cum dolor aut magni culpa. Sit quia laboriosam dignissimos quia sit ratione sequi. Rem blanditiis ut et ducimus mollitia hic eius. Aliquam labore rerum nisi et fuga quia. Dolorem aliquid voluptas dolore praesentium asperiores. Quia optio eum ut nemo et. Repellat consequatur rerum qui nisi. Cum omnis aspernatur numquam quidem nobis mollitia sequi. Sunt distinctio id dignissimos voluptas. Nemo omnis et delectus dolores qui rerum.','aperiam-minima-omnis','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(3,'ut fugit','1654587132.jpg','Placeat cumque quae velit nostrum. Et aut aut et aut aliquid cum nesciunt. Amet minima consequatur consequuntur quia saepe consectetur libero. Et libero cupiditate et vel sed suscipit eum. Tempora et fugit repellat facilis ipsa. Dolore aut in occaecati quibusdam aliquid. Assumenda neque tenetur et provident asperiores aliquam qui reiciendis. Expedita repudiandae odit voluptatibus est accusamus dolor. Velit voluptatem eligendi aut. Impedit eum asperiores culpa itaque magni. Laudantium qui repudiandae maxime similique aut. Ratione ad cupiditate aperiam eveniet quibusdam qui. Eaque laboriosam et omnis eius. Illo quo enim placeat voluptatem sint. Tempora quod neque eum labore. Molestiae excepturi id ipsa delectus. Sint nihil quia autem quisquam. Enim nemo quis accusantium perferendis corporis mollitia. Officia architecto sed laudantium nihil. Hic debitis dolore libero eaque quia. Quaerat iste officiis ex omnis rerum. Eligendi earum qui provident placeat voluptas dolor molestias. Eaque et qui delectus ab. Deserunt et laborum iusto eaque inventore sint. Aut dicta et placeat rerum impedit. Iusto dolorem temporibus dicta ipsam. Numquam voluptatibus odit natus excepturi distinctio nemo ut excepturi. Nesciunt provident tenetur et vitae quidem error nulla id. In accusantium possimus illo quo voluptatibus architecto quo. Tenetur corrupti ea eligendi.','eos-eaque-qui','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(4,'voluptatem cupiditate','1654587132.jpg','Saepe at doloribus minus fuga voluptatibus. Nulla error sint illo neque alias. Qui velit aut ratione minima. Laborum autem dolorem similique voluptatem culpa corporis. Qui temporibus itaque excepturi quasi in. Porro sit accusamus voluptas ipsum. Est exercitationem inventore maiores nihil sed. Iure eos ut omnis ex rem omnis adipisci. Quia sunt quo suscipit corporis non. Voluptatibus expedita excepturi non ipsum nihil et dolorum. Praesentium iusto eligendi doloribus molestiae. Et ad porro aut ipsum praesentium. Explicabo alias a nostrum ea et sapiente omnis. Temporibus saepe et excepturi distinctio facilis. Est quia exercitationem dolor laboriosam delectus nemo id perferendis. Quibusdam hic eaque aut blanditiis sunt voluptas porro. Suscipit ipsa repellat excepturi vitae beatae nulla. Ut facere enim blanditiis. Voluptatem nisi tenetur vero. Ad et enim in quisquam error ut provident. Repellendus rerum quae nostrum ut alias et. Iste quo sapiente natus voluptatibus fugit corrupti beatae. Et itaque dolores voluptatibus voluptatem. Perferendis aperiam autem id et nihil voluptatem. Aperiam nihil dolorum aspernatur neque culpa commodi. Officia exercitationem molestiae aut. Aut natus voluptas laboriosam ea et accusantium esse commodi. Cumque voluptates dicta facere dolorem ea. Cumque optio totam quis delectus eaque. Fugiat perferendis pariatur fugit ut.','itaque-expedita-libero','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(5,'quo tempore','1654587132.jpg','Itaque tenetur nesciunt non corrupti. Quam ea ex reiciendis quas delectus non. Laudantium vel facere sunt atque nihil aut. Architecto perferendis maxime magnam non iusto perferendis. Nesciunt et officiis officia aperiam occaecati aut. Autem magnam cum voluptas nam ab. Iste quo dolorum ut odio id optio fugit. Ex debitis sint alias. Sunt consequatur et delectus quod. Quibusdam ratione cumque laboriosam doloremque sit. Quibusdam laborum fuga ex laborum. Quidem ut aliquam sit quam porro at. Harum ut quaerat odio. Voluptatem adipisci corporis vero ut cum rerum aut. Ab minima ab recusandae sit sint at cumque. Blanditiis tempore magnam qui fuga earum cumque consectetur iusto. Sunt voluptas possimus cupiditate quia quam optio. Et et quo debitis illo molestiae fugiat iste. Et magni facilis voluptas ut voluptas sed. Rerum placeat sit nobis voluptatibus ut. Et animi consequatur corporis incidunt. Error aspernatur autem similique necessitatibus aut. Soluta aut blanditiis perspiciatis maiores non quo. Et omnis eos dolore aperiam esse non. Sint placeat voluptatum et quidem hic vel autem. Dicta aspernatur qui ea sit ad et est. Ipsa doloremque ducimus ullam placeat placeat omnis. Provident reprehenderit qui voluptatem impedit consequatur. Distinctio atque quia itaque est facere. Sed deleniti architecto impedit sunt cum et.','ducimus-ut-non','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(6,'fuga impedit','1654587132.jpg','Tempora eligendi repellendus eius quia eum. Et non velit nihil aliquam quod. A velit ut modi quia eveniet voluptatem quia. Consectetur maiores cumque cupiditate et deleniti voluptates doloremque. In sed consectetur vel consequatur facere. Aperiam possimus doloremque suscipit ad sed numquam asperiores a. Esse aut velit voluptate voluptas facere eligendi voluptas. Omnis repudiandae hic aut qui. Alias non ut voluptatem voluptate dicta et sint. Voluptatem deserunt ut blanditiis fugiat ut ut. Maiores id et sint nostrum et fugit. Ea aut non vitae voluptatem ratione rerum ullam. Rerum ut ratione ut et eum cupiditate ex voluptatem. Maxime nisi vel asperiores eaque officia maxime odit. Illo et placeat mollitia vitae quia corrupti sunt. Et assumenda nam qui voluptas magnam. Rerum aliquid blanditiis possimus iste in quis odit sint. Iste labore vero et provident consequatur numquam. Qui minus qui ab iste ullam. Nisi quas quae repellendus ut sit quis molestiae aut. Nesciunt perferendis necessitatibus minima illum. Ratione expedita quasi ut quidem vel ex. Unde voluptatem in qui et unde. Et quasi ut error rem. Aliquam hic quod eligendi voluptas. Ut voluptatum ut repellendus adipisci fugit alias. Quod rerum sunt ipsam quo magnam libero totam. Culpa dignissimos quo ad ea quaerat quisquam. Rerum aliquid velit ad perspiciatis sint possimus. Molestias quam numquam quaerat doloribus quasi voluptatum.','quia-sit-distinctio','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(7,'possimus sed','1654587132.jpg','Et recusandae dolores alias modi. Quia eaque omnis vel. Totam qui architecto aut ut eveniet ea et. Similique eaque aperiam aliquid earum. Voluptatem esse aliquid iure aut et asperiores voluptatem laborum. Animi nam neque qui officia distinctio fugit quae. Molestias in quasi iste consectetur ut qui. Numquam deleniti dicta sed perferendis. Non tenetur illo vero qui non sit. Modi a sunt id voluptas nisi. Similique est expedita velit nam eum. Dolor tenetur a odio maiores voluptatem nostrum. Odit voluptatem aut consequuntur officiis magni. Ut sint omnis aut eaque eveniet quia et. Quas explicabo beatae a alias perferendis. Quisquam ipsam ipsam error accusamus. Ut eum ut optio voluptatibus voluptates veritatis voluptas. Est quisquam tenetur libero omnis necessitatibus. Sint dolor aut deleniti. Ipsa sed sunt porro excepturi quam deleniti consectetur. Placeat sunt dolor dolorem sed. Aliquam amet suscipit rem eos accusamus consequuntur incidunt voluptas. Eveniet sit rem consequuntur architecto repellendus. Quibusdam dolore impedit voluptatem nostrum perspiciatis. Distinctio eligendi in dolores nemo molestiae reiciendis. Atque quos assumenda illum veritatis. Expedita sint aut quasi aspernatur rerum praesentium. Ut repudiandae quo minus sapiente ex dolorem. At dignissimos consequuntur qui aspernatur commodi fuga rerum. Voluptas aspernatur temporibus accusantium ipsum veniam voluptas placeat.','doloremque-sit-minima','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(8,'nihil ipsum','1654587132.jpg','Officiis repudiandae et fugiat. Est voluptatum consequatur suscipit veritatis optio sed. Molestias ut quidem perspiciatis quo quisquam repellendus. Rerum qui pariatur exercitationem expedita et officiis sit. Deserunt voluptates et eligendi at. Occaecati beatae in quae ea maxime. Quis nihil repellat aut natus voluptates est ad. Et et repellat aliquid quos voluptatibus unde maxime. Modi aliquam iste voluptatibus aut. Sint quia maiores mollitia temporibus reprehenderit dolor. Aut fuga et accusamus voluptatum. Quam repellat necessitatibus repellat distinctio sequi vero cum. Quis sequi eos nobis non alias quod amet. Distinctio illo dolor voluptates. Et atque qui assumenda laborum labore. Ut qui ut mollitia ea mollitia voluptas non. Mollitia dolor exercitationem tempora dolor sit. Debitis et libero amet est vero tempora voluptatum. Voluptatem aut rem dolore. Dolore eum nisi et soluta commodi sed dolores nobis. Qui enim saepe accusamus nihil. Eos mollitia voluptatem non qui. Voluptas optio sapiente aut ut. Nisi et hic in iusto dolorem et quis. Excepturi aliquam nostrum consequuntur. Excepturi facere exercitationem voluptatem tempora cum. Qui non aut ipsa minus pariatur. Ut sit voluptatibus harum aut ab nisi corporis. Soluta reiciendis natus fugiat tempora numquam voluptatem. Cupiditate qui enim ut ea rerum eius.','aut-facilis-illo','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(9,'accusamus et','1654587132.jpg','Quam laborum voluptatem et ut eos dolor. Qui laudantium impedit voluptatem. Tempore vel consequatur delectus enim nihil natus. Provident cupiditate doloribus aut et. Quo autem qui fuga consequatur dicta voluptatem voluptatem. Modi illo dignissimos ut sed velit. Tenetur eaque cumque aspernatur non iste. Aut ea aut quam quia. Consequatur debitis et cum repellendus. Nobis soluta asperiores eaque expedita quasi quia. Porro velit atque incidunt nobis. Consequatur rem et doloribus occaecati pariatur vitae odio. Iure perferendis non officia nihil rerum aut vitae. Cupiditate alias blanditiis quae. Voluptatum enim aperiam reprehenderit libero. Pariatur officia possimus officia sapiente atque qui quos. Assumenda eum ullam consequatur rerum ipsum aut aut. Eaque recusandae consequuntur modi eos vitae qui. Sed esse ex magni dolores. Exercitationem distinctio quo quo nam enim sunt. Cumque sed numquam eveniet laborum delectus. Ducimus aut omnis qui aut. Quis illo placeat non ipsa. Ipsam nam alias cumque exercitationem quisquam molestiae. Quo molestiae voluptate corrupti illo. Illo quos aut aliquid illo error illum. Deserunt aut beatae quam sunt ad aut. Nam provident pariatur dolor exercitationem. Temporibus ipsa et sed vero iusto aperiam pariatur. Minima asperiores id corporis similique.','nobis-molestiae-ad','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(10,'animi eos','1654587132.jpg','Omnis et illum vero impedit quia non magnam. Et ut atque temporibus distinctio quo eius praesentium voluptas. Aut omnis illum minus aperiam officiis. Ex eum ullam id modi non. Perspiciatis recusandae quod autem. Est nostrum molestias nihil delectus libero officiis. Enim atque quis tempore molestias nostrum. In quis rem provident officia. Quo atque inventore nulla pariatur non aut voluptatem voluptatem. Unde ipsam quis quidem ut. Perferendis quae in consequuntur aut quas magni. Necessitatibus cupiditate ut voluptatum et. Voluptatibus maiores modi ratione minima nesciunt. Sed molestiae quibusdam libero corrupti laborum labore. Sit et et maxime sit aliquid. Vel enim ipsam delectus nam. Alias id et modi quia assumenda et. Consectetur rem quia ab iure rerum. Veritatis molestiae sed consequatur nihil fugit. Non voluptatem ut aut vitae consequatur voluptatem qui itaque. Dolor libero hic possimus. Minus dolor cupiditate odio in. Laudantium aspernatur ut non aliquid veritatis fuga. Sapiente rerum dolore voluptatum voluptas voluptas commodi quam soluta. Dolorem quo aut quo labore quis sint ut incidunt. Error sit ullam vel quia. Saepe consequatur nihil quas omnis. Nemo qui quam qui dolorem autem fugit alias fugit. Pariatur fugiat fuga sint. Nihil alias perferendis quia hic qui repellendus eligendi.','molestias-quo-assumenda','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(11,'id eum','1654587132.jpg','Odio beatae adipisci soluta quasi. Odit amet porro ipsam corporis accusantium. Id quisquam temporibus facilis fugiat qui neque soluta. Molestiae vero omnis vel omnis molestiae. Et excepturi eveniet id fugit optio quo. Deleniti nobis ipsa ratione pariatur non eius. Aut maxime eius id ut ullam ullam placeat magni. Sit non at nostrum reprehenderit amet. Dolorem aut rerum deleniti eos molestias et. Nulla qui facilis alias vitae ut ut et. Eligendi modi et molestiae tempora. Deleniti voluptatem numquam rerum quis neque at. Magnam provident molestias qui voluptatem. Alias vero soluta et quibusdam. Ut enim dolore officiis officia maiores sequi et. Aut recusandae ut reprehenderit provident in hic. Veniam maiores ex facilis quos voluptatem. Ut tempora occaecati velit ea qui. Ipsa architecto culpa est in minima animi qui. Dolorem aliquam sint est enim est ea. In commodi voluptas culpa facilis ipsam voluptatem ex. Ipsam quibusdam hic repellat sunt quia. Ut in et magni et. Ducimus est voluptatem expedita dolore sunt consequatur. Hic similique velit ducimus eligendi dolores architecto assumenda. Quam error animi qui laborum explicabo ut enim. Eos voluptas nam non vitae corporis reprehenderit eos. Doloribus impedit officia mollitia culpa est. Vero veritatis et et doloremque voluptas exercitationem. Voluptatem velit optio nihil quam.','minus-repellendus-natus','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(12,'incidunt voluptas','1654587132.jpg','Non vitae earum vitae aut ut esse. Nisi repellat nihil voluptatem soluta aut. Minus esse voluptate blanditiis omnis et quia consequatur vitae. Modi et vel dolor eum aut dolores ut. Commodi tenetur ea iste tenetur voluptatem minus et. Eum iste vel vel sed qui. Ipsam ullam dicta mollitia eligendi exercitationem. Perferendis explicabo quia iste culpa eos. Maiores ut ullam omnis nisi. Numquam qui non quod autem harum. Velit nam recusandae ipsam earum odio ullam. Id repellat tempora et id tempore tenetur. Vitae ea porro saepe dolor est numquam sit voluptas. Omnis illum quia ut occaecati earum. Consequatur commodi nisi repellendus. Quisquam amet sunt laborum aut. Delectus consectetur non totam. Et unde aliquam nihil sint eaque excepturi. Sunt accusantium quo ea doloribus illum corrupti vel. Sint vel ut sunt accusamus occaecati. Fugit eaque numquam sapiente magnam. Corrupti exercitationem facere molestias provident eos nesciunt quidem. Voluptatem facilis sapiente unde fugiat consectetur at. Eius accusantium facere est cupiditate odio. Sed id enim nobis laboriosam. Eos voluptate labore quis delectus possimus beatae ut. Consectetur et quia assumenda sunt aut expedita molestiae. Aut sunt sequi molestiae non voluptatem eius omnis. Aut consequuntur voluptatem nostrum vero maiores a. Porro sed et repellendus ut suscipit.','quisquam-qui-distinctio','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(13,'quod eveniet','1654587132.jpg','Eum debitis aliquid aperiam reiciendis. Et error odit praesentium est. Ut quas laboriosam omnis vel cumque molestias provident quia. Sed optio exercitationem suscipit et sunt ullam commodi. Qui esse voluptas et reprehenderit debitis quis a. Asperiores consequatur deserunt consequatur molestias cum nostrum hic. Dolores voluptatem quibusdam harum possimus et fuga. Recusandae officia ut minima recusandae et. Accusamus sunt delectus iure qui. Repellat aliquid vel blanditiis ad deserunt occaecati. Ea quidem voluptatum voluptas autem eum. Placeat distinctio et vitae rerum. Consequatur mollitia sed sequi quisquam qui. Quae ducimus et cumque aut doloremque et nesciunt. Debitis voluptatem aut earum eum dolores excepturi. Nihil est veniam itaque est exercitationem. Repudiandae quia praesentium iste et. Molestias consequatur expedita aut et autem. Facere et exercitationem dolorum ipsam enim ipsa consequatur impedit. Vel eos facilis nobis sit dolor totam occaecati. Est voluptatibus magni dolor aut. Voluptatem dolores aut dolorum nam ut illo quam. Repellendus modi est ducimus reprehenderit ex nobis. Deserunt omnis quia nihil aut minima debitis repellat. Assumenda dolorem doloribus dolorem vel. Voluptas adipisci adipisci aspernatur quia. Officiis alias omnis et qui culpa. Quisquam aperiam sint nihil beatae ut. Harum maxime consectetur minus enim. Iste sit sed sit mollitia.','cum-accusamus-non','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(14,'sapiente architecto','1654587132.jpg','Quidem illum laborum repellat vel magnam tenetur sit. Aliquam nemo et dolor repellat. Amet accusantium sit dolor nam qui consequuntur autem. Exercitationem quod quae quisquam corporis ipsa. Voluptas culpa assumenda officia repudiandae. Ex qui laboriosam pariatur non numquam culpa placeat. Quia consequuntur culpa asperiores est sequi et non. Nam reiciendis ut voluptatem qui qui ducimus mollitia. Ut rerum inventore fugit non minima. Cupiditate iste ea earum at. Ad officia eum provident et incidunt sed veniam. Ut ea ex aut voluptatum. Minima quia qui quaerat facere iste. Ipsa et et nesciunt. Unde commodi nesciunt laudantium ea. Esse perferendis facilis deserunt enim temporibus. Nostrum a consequatur laudantium ipsum quidem est. Aliquid in dignissimos voluptatum veniam. Error eos cupiditate incidunt sit quis. Qui voluptatem dolores ut illo sequi adipisci quos. Consequatur voluptatem commodi quia qui. Explicabo voluptas eveniet eveniet cupiditate incidunt quod. Atque dicta id officiis architecto. Enim earum quod quibusdam autem sapiente sit et. Labore perferendis omnis tenetur. Quae architecto ducimus adipisci voluptates magnam et repudiandae. Culpa repudiandae esse doloribus nam dolorum. Eius corporis ut sed quidem nihil repellendus pariatur aut. Voluptates id in dolorum aut non debitis minima et. Perspiciatis at quidem ullam voluptatem.','a-laudantium-debitis','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(15,'libero consequatur','1654587132.jpg','Maiores voluptatem aspernatur adipisci sint quo aut ex. Nam saepe molestias nihil reprehenderit. Optio possimus reiciendis consequatur sed et maxime unde. Laudantium at nam dolorum quas. Commodi voluptas expedita quis in commodi. In sit ad iusto et impedit ipsa. Corporis vel est et molestiae dolores quo dolor ut. Odio assumenda qui necessitatibus. Qui culpa nesciunt fugiat facilis sequi et qui. Eaque sint aliquid molestiae. Dolorem minima dolorum possimus in laudantium et consequuntur ad. Sequi quo ea et in quis dolorem unde. Iure recusandae blanditiis non velit nostrum. Eaque dicta dicta quidem veritatis sunt culpa. Voluptatem enim voluptate voluptatem voluptatem. Ut sed velit fuga. Sunt provident id facilis architecto fuga fuga. Eum deleniti ab repellendus. Animi quam esse nemo. Voluptas harum et ut ut et debitis. In odit qui debitis. Ut voluptatem ea occaecati possimus. Voluptas consectetur aut est similique maxime dolor. Hic sit dolor quisquam sed inventore non repudiandae. Voluptas doloremque est dolores enim dolorem. Dolor eum qui officiis nam exercitationem porro enim. Qui asperiores modi voluptatibus magni. Fuga aperiam dolorem dolores voluptates totam dolores delectus. Magnam quis sunt reiciendis sequi. Doloribus et libero distinctio expedita odio enim.','dolores-eius-ratione','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL);

/*Table structure for table `blogs` */

DROP TABLE IF EXISTS `blogs`;

CREATE TABLE `blogs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `blogs` */

insert  into `blogs`(`id`,`title`,`image`,`description`,`slug`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'suscipit','1654587065.jpg','Dolor delectus rerum nemo qui ab debitis. Officiis sed unde saepe labore dolor. Aut illo asperiores iusto quaerat repudiandae. Nesciunt deleniti accusantium placeat accusantium aut. Cupiditate dicta suscipit dolorem vel. Omnis et at vel accusamus. Blanditiis magni et minima omnis ipsum sed provident. In voluptas id dolores voluptatem saepe delectus est incidunt. Hic totam accusamus alias distinctio sit dolorum. Ducimus nulla ut veritatis. Soluta corrupti adipisci ut sit. Mollitia totam consequuntur ad quibusdam quia fugit. Ad maxime reiciendis fuga saepe quia commodi repudiandae. Dolore explicabo minus sint molestiae maxime in. Reprehenderit pariatur dignissimos alias aut adipisci optio. Odio sed id non et eum maiores libero. Sunt repellendus reprehenderit repellendus. Est enim quod quidem placeat expedita. Natus sit facilis qui et. Rem omnis sit quia dolore. Fugiat in voluptatum placeat. Voluptatibus perspiciatis modi fugit eaque laboriosam voluptas enim ut. Aut molestias dolor omnis est perferendis quod tempore magnam. Quasi dolor nihil in et qui accusantium consequuntur. Minima voluptas maiores eius et reiciendis iusto ab. Enim et nisi doloremque itaque. Facere aspernatur sed eaque dicta quod ut. Amet sit temporibus consequatur blanditiis incidunt aspernatur molestias autem. Qui quia dolores voluptatem molestiae distinctio atque minima repudiandae. Maxime cumque consectetur fugit voluptas aspernatur. Accusamus odio repellendus et enim aliquid in dolor. Assumenda quia explicabo voluptate quo deleniti aperiam modi. Voluptatem numquam ducimus eos molestiae eligendi est aperiam. Aliquam perspiciatis vel deleniti. Sit animi magnam quibusdam quod fugiat non qui. Repellat voluptatem ut voluptatem saepe totam at. Rerum cupiditate possimus architecto perspiciatis ut in nulla quas. Aut fugiat excepturi id earum numquam. Nemo corrupti quibusdam quia nulla aspernatur ex dolorem. Voluptatum nisi libero quia vitae quae.','reiciendis','2022-06-07 07:29:25','2022-06-07 07:31:05',NULL),
(2,'quasi','1654587065.jpg','Omnis natus autem vero sit maiores esse blanditiis cupiditate. Eius cupiditate voluptatem quod dignissimos. Reiciendis ut non officia. Rem qui nisi eveniet eveniet sit. Perspiciatis aut vero neque. Voluptatem minus pariatur velit delectus. Dolore qui perferendis ducimus odit est. Iusto adipisci quia quod quod repudiandae ut veritatis facilis. Architecto quia architecto nulla sunt laudantium aut itaque autem. Aut aut iusto iure rerum. Qui nostrum aperiam suscipit est repudiandae ratione. Deserunt aut sunt dolor eaque blanditiis architecto. Nisi asperiores sit enim iure qui quod. Dolores a similique et corporis deserunt nihil. Est reiciendis itaque corrupti recusandae cupiditate quisquam nihil. Fugit in aut doloribus qui voluptas enim laudantium. Eos qui ipsa aut. Nobis aut ipsam dolor et accusantium eveniet facilis. Ipsum tempore consequatur voluptate. Pariatur qui adipisci nemo inventore corrupti voluptas animi. Amet laudantium perspiciatis corporis occaecati alias modi quos. Tempore sapiente commodi commodi error quisquam. Nesciunt voluptatem ut autem voluptate et vel recusandae. Dolore animi est beatae occaecati sed recusandae. Ipsa vitae quibusdam velit magni enim repudiandae sit quae. Vero ullam veniam id enim dolorum numquam omnis. Accusantium autem quae sit ad recusandae velit ad. Qui et ad sapiente tenetur doloremque. At sunt minima quia ut. Aut et aut qui modi illum quibusdam possimus. Nesciunt quo ut nihil odit accusantium pariatur. Numquam consequatur perferendis et neque voluptatem qui tempore. Aut consectetur similique exercitationem. Quia qui autem architecto sunt quidem. Quaerat pariatur itaque assumenda eveniet labore est in. Eum delectus id aliquam ex. Non provident modi sequi. Quia quia aliquam quis error expedita cumque deleniti. Reprehenderit iure inventore sit magni. Nihil pariatur omnis illum et delectus voluptatibus fuga.','cupiditate','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(3,'nulla','1654587065.jpg','In sed quae quasi dolor molestiae soluta voluptates omnis. Consectetur reprehenderit occaecati voluptate blanditiis. Necessitatibus velit dolorem quaerat voluptatibus sed assumenda. Quis exercitationem eum eaque in error. Deleniti nihil et sit consequatur dolorum non. Aut voluptas molestias quisquam optio quibusdam impedit natus. Vitae debitis consequuntur ipsa beatae quasi aut nobis. Adipisci est est ipsum ut ex aut. Inventore id aut exercitationem omnis. Ut cupiditate aspernatur ea et. Ut porro reiciendis omnis quia totam fugiat cum. Aut debitis qui possimus autem neque provident dolores aliquam. Ex sed blanditiis optio quibusdam illo qui ratione. Quis autem porro nihil earum corrupti velit velit placeat. Sint quibusdam ut illo ut vitae nisi non. Quos ducimus dolorem aut. Perspiciatis odio sit eligendi est ut sed. Quia totam quidem consequatur itaque nulla beatae. Et itaque consequatur beatae et fugiat et. Qui maxime soluta nulla facilis facere veritatis ratione. Accusantium totam laboriosam fugit nobis autem. Quaerat ullam perferendis consequuntur quae corrupti quasi sint. Corrupti eius corrupti inventore quia. Est repellat quo consequatur quidem reiciendis ipsam. Totam et labore aut hic qui. Possimus officiis numquam corrupti rerum rerum eum. Atque animi aut voluptatibus eveniet. Et illum dolor dicta quia praesentium pariatur. Voluptate tempore ullam sint necessitatibus voluptatem est expedita. Cum soluta et tenetur atque ex. Est vel dicta non dicta voluptatem quia. Quo necessitatibus eos ut sit. At cumque voluptas earum iste. Hic qui vel ea expedita enim est. Quasi eos quo quam vel occaecati fugiat. Magni ex doloremque blanditiis maxime sit vitae voluptatum. Nemo assumenda perspiciatis repudiandae architecto. Non delectus laudantium ut repudiandae dolorum. Eaque repellendus voluptas et consequatur odit. Qui sed consequatur ex ea.','aut','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(4,'laborum','1654587065.jpg','Voluptate totam cupiditate sed asperiores deserunt sequi consectetur. Incidunt aut voluptas eius blanditiis similique. Repudiandae quia quia tenetur. Voluptas beatae facilis sint consectetur. Suscipit magnam excepturi consequatur aperiam sit. Ea voluptatem qui voluptas consequatur rerum. Et impedit et sed rem qui dolores qui. Accusantium omnis odit fuga aperiam. Eum est non laborum adipisci. Nulla ut aliquam inventore laudantium at velit dolores. Reiciendis aut consequatur vero qui quia corporis. Dolorem quis enim qui est. Autem eligendi est aut cumque ducimus. Explicabo maiores quis minus aut ullam sit. A in quas voluptatem eum quibusdam. Tempora voluptatem rerum officiis totam tenetur sit omnis dolorum. Molestias et ut omnis. Laudantium nulla voluptas illum dignissimos autem eaque repellendus. Dolorum quia error cumque eos ea est. Explicabo consequatur asperiores modi similique laboriosam voluptas. Atque tenetur ut sed quas accusamus voluptatibus minus. Voluptatem voluptas veniam ut quibusdam. Eveniet optio maxime quia officiis error libero. Delectus sit facere aspernatur sint. Est molestiae omnis exercitationem vero iure. Vel nemo fuga aliquid iste quasi assumenda. Hic qui maxime perferendis. Ipsa quia repudiandae laudantium ut dolorem. Consectetur harum sunt sunt suscipit quo nam amet. Et ea exercitationem id quaerat sed illum soluta. Facere asperiores ex velit odio aliquam non nam. Consequatur nihil omnis beatae quis. Ipsa dolore sit magni cumque similique odio. Quos aut qui iste nam aut est. Consectetur vel cumque qui culpa consequuntur odit nulla. Sint rerum tempora animi sit officia ut sint error. At ut qui autem consequatur error ut pariatur quisquam. Nostrum quia repudiandae repellat sed voluptas cumque magni. Sunt harum eos numquam aut. Doloremque ducimus eius exercitationem id harum.','aliquid','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(5,'qui','1654587065.jpg','Vero quod nemo voluptatem est voluptatem. A recusandae fugiat et. Enim ullam optio in aut. Nisi est ipsam consequatur velit consequatur. Architecto magni suscipit rerum ratione. Ducimus in consectetur et est sed vitae nesciunt. Cum id cumque sit. Deserunt perferendis perferendis distinctio tempora nulla ut odio. Qui quae aliquam distinctio non ducimus aperiam. Velit iste iusto rem corrupti necessitatibus. Dolores neque est temporibus ipsa voluptatem. Minus asperiores soluta architecto repellat. Similique exercitationem exercitationem sed placeat. Enim reiciendis aut laudantium necessitatibus. Explicabo et ratione temporibus eius sed. Beatae quo beatae voluptatem. Ullam totam corporis libero qui. Quos debitis numquam sint illo iste. Sapiente aspernatur tempore quia ut dicta consequatur. Nihil eum totam ut ea. Consequatur alias tempora est impedit nemo animi nobis. Hic similique velit id nobis quia quae. Ex optio nostrum sequi voluptas voluptates. Dolore recusandae rerum qui dolor eaque velit cumque aut. Sit dolor nostrum repellendus harum. At cumque aperiam odio accusantium. Beatae et perferendis consequuntur et et dignissimos provident. Aut velit sapiente rerum sequi tempora. Asperiores sint et dignissimos quis sed. Autem adipisci esse non alias. Aut aperiam voluptatum harum quisquam ab rem vel. Consequatur consequatur eaque officiis ut perspiciatis omnis. Sed rerum odio non aperiam aperiam reiciendis officiis. Quasi hic non officia facere aliquam similique. In nisi reprehenderit ut dolores impedit. Quos molestiae quo similique illum odit sit. Autem sed alias non error distinctio sit. Enim ut temporibus provident ipsum ut nulla non rerum. Recusandae minus et et ipsa vel. Repudiandae velit suscipit sit harum cum.','illum','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(6,'quas','1654587065.jpg','Iste exercitationem ut excepturi a aliquid non impedit. Aliquid voluptatem et impedit eos reiciendis. Beatae qui sed labore tempore vel quos voluptatem accusamus. Asperiores modi aut animi. Est iure dolores enim sequi molestiae minus. Voluptate culpa qui dolorem fugiat sequi cumque porro. Ea omnis temporibus aperiam quidem dolore eius. Rerum aspernatur eius aut temporibus. Eveniet optio voluptatem et. Ex mollitia est magni aut aperiam incidunt ut repellat. Atque mollitia dolorem debitis voluptatem sunt. Rem laborum alias voluptas commodi est. Quis laborum iusto eum nemo similique vel laudantium. Consequatur distinctio harum tempora iure maiores hic est. Perspiciatis praesentium voluptas dolorem. Maiores deleniti reiciendis atque occaecati voluptatibus. Velit dolorem nemo molestias voluptatum ipsa doloremque. Laborum fugit ex doloribus et. Deserunt rerum labore voluptatem et quod ut. Sunt dolore est impedit aut incidunt. Nostrum nobis ut iure iusto quos. Iusto libero cum sed voluptas quisquam tenetur. Qui tempora facilis labore nesciunt. Rem iste dolor mollitia eos ipsam. Ducimus harum qui illum error error ab. Debitis dolores minima repellendus harum. Quia qui animi ut quia pariatur qui impedit. Est voluptas culpa officiis laudantium maiores qui aut. Quas autem sed quidem placeat doloribus. Et voluptatum a quae aspernatur dolores rem. Occaecati eum odit illum reprehenderit enim. Magni excepturi non quisquam temporibus facilis consequuntur veniam. At aut sunt excepturi molestiae. Vel et officiis ea. Rerum perferendis dicta est nobis necessitatibus minus aut. Temporibus est dolor iste at. Autem fugiat porro iure aliquid delectus rem. Expedita itaque est cupiditate atque deleniti. Et vel suscipit animi inventore minus culpa et. Corporis velit aut et est.','fugit','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(7,'facere','1654587065.jpg','Voluptatem ut dolorum fugit est repudiandae tempore beatae dolor. Ullam similique ratione iure qui autem distinctio libero. Esse cum numquam dolorum consectetur exercitationem nam neque. Et pariatur blanditiis occaecati. Facere quae et sed atque eum. Nulla aliquid non autem unde. Laborum id voluptatibus quo ducimus. Alias neque magnam eos nemo. Minus aut amet nobis eos repellat. Beatae ipsa eos quia deserunt amet consequatur quaerat. Provident aliquid vel dolorum aut nemo. Dolore asperiores repudiandae aut illo vel ex. Et est dolores aspernatur vitae qui. Nobis harum laborum facilis aliquid. Non est voluptatem sequi blanditiis maiores facilis et. Quas et repellendus velit vitae pariatur id natus provident. Exercitationem consectetur perferendis illum recusandae voluptatibus similique earum. Debitis eaque aut quam facilis rerum aut provident. Quae sint unde sed ut rerum tempore perferendis illum. Ad facilis sequi delectus qui expedita et. Explicabo expedita quo ratione dolores id. Perspiciatis et sint vero velit. Quis cumque ipsam eum sapiente nemo. Nobis sit ut qui maiores perspiciatis et reiciendis totam. Quam non molestiae consequatur natus occaecati. In quos aut ut occaecati. Cumque molestiae voluptatem molestias sapiente. At sequi et molestias autem rerum est sint est. Quae qui quis architecto. Sit iure labore corporis labore iste minima. Dolorem esse perspiciatis veniam at. Cupiditate aliquam ut quibusdam praesentium. Commodi veniam repudiandae ex occaecati. Necessitatibus rem dolorum debitis dolore. A et unde sequi nulla molestias. Earum libero quia et necessitatibus odit. Esse qui quam in vel ut. Harum rerum dolorum ut suscipit porro qui. Ab sint ex quo minus provident laboriosam ex. Est nesciunt quia sit consequatur molestias.','aut','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(8,'perferendis','1654587065.jpg','Repellat in voluptate quae asperiores et harum. Labore commodi sapiente mollitia dolore autem ut. Quis excepturi nostrum dolores dolor. Velit quos asperiores libero qui et aut. Voluptatum ratione rerum aliquid quas incidunt ex ut. Optio quam possimus ipsum deleniti laudantium expedita voluptates. Doloremque quibusdam autem nemo. Est adipisci quia dolorum ut aspernatur a minus. Voluptatem occaecati iusto expedita voluptatem delectus. Aperiam dolor adipisci rerum consectetur est ratione. Error cum nostrum maxime tempora ullam sit. Deserunt ad exercitationem provident ducimus dolor qui. Eum omnis voluptates aut similique fugit at. Odio consequatur doloribus qui aliquid et id. Doloremque ratione id tempore dolore molestias a. Ex corrupti ad veniam eligendi. Esse dolores vitae fugit quis asperiores optio saepe. Enim voluptatibus rem quo nostrum. Ipsam dignissimos consequatur et temporibus explicabo vero. Minima non natus quis. Beatae molestias deleniti in earum recusandae consequuntur. Exercitationem tenetur eius dolorum excepturi. A reprehenderit quod consequatur eaque. Quod dolor delectus delectus. Explicabo voluptatem id excepturi ab excepturi. Tempora reiciendis sed velit in voluptatem odio aut. Laborum et laudantium in cumque possimus non. Rerum aliquid porro et autem et quia quidem velit. Possimus libero quos nobis quasi qui sint unde. Et iusto ut aut ut voluptatum. Ratione architecto consectetur labore cum velit modi. Deleniti eum explicabo dolores nam. Cum aut et architecto corporis eum nobis. Occaecati mollitia doloremque ducimus consequuntur et architecto. Illo voluptatem quidem ipsam est possimus inventore. Debitis placeat illum nihil consectetur. Asperiores hic sed sit omnis voluptas. Aut saepe dolor molestiae provident beatae voluptate. Et facere magni consequatur voluptatibus. Id rerum dolor illo eos beatae quis necessitatibus.','eum','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(9,'inventore','1654587065.jpg','Dolore enim facilis rerum ipsa voluptas. Sunt nulla doloribus dolore et nam dolorem voluptas. Nulla eveniet hic ut doloremque accusantium. Dignissimos in accusantium velit quia quis. Minima minus velit id veniam natus maxime nihil. Delectus et hic libero. Autem voluptas tempora nostrum rerum libero. Aspernatur fugiat et exercitationem illum quidem cum. Dolorem vel dolorum voluptatem aperiam dolorem occaecati. Debitis expedita consequatur totam quis nulla. Non ut tempora odio. Voluptas quam iste in nostrum est quod voluptatem laborum. Tempore rerum dolor porro soluta. Explicabo officiis quo fugiat molestias reiciendis fugiat error. Fuga quis ut ad sit et et. Rerum iusto libero rerum. Corporis rerum vel ut ut in. Eos deserunt necessitatibus amet nostrum dolore et. Et consequatur perspiciatis quam distinctio quo. Sequi pariatur eos praesentium omnis culpa qui. Sunt cupiditate corporis sed velit recusandae. Explicabo omnis laboriosam sunt voluptas fugiat quos alias. Id omnis dolores facilis sit. Nisi corrupti est voluptate unde necessitatibus quia tempore. Voluptatem ducimus sunt laudantium non sunt iusto consequuntur voluptatem. Sint voluptatem error ducimus ex saepe voluptatem dolorem. Praesentium ab amet ex consequatur ad excepturi. Sunt saepe voluptate eum repudiandae est iusto in. Eius animi quia nesciunt dolores quas fugit illo. Adipisci non voluptas est sed facilis totam perspiciatis. Aut ut quisquam porro amet reiciendis culpa. Aut aut id ipsam. Perspiciatis eos nostrum est repudiandae exercitationem et. Laborum harum ut rerum possimus consectetur qui quis. Suscipit quidem dolor ratione ut ut dolor dolore quis. Quia aut adipisci temporibus tempore consequatur. Et quas aut deserunt dignissimos. Neque adipisci doloremque provident similique molestiae maiores consequatur. Aliquid a voluptatem quia rem quo ipsum aut odio. Maiores voluptate possimus hic qui porro ipsum.','et','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(10,'animi','1654587065.jpg','Aut ut accusantium sint incidunt consequatur quaerat modi. Beatae voluptatum odit nostrum et blanditiis. Voluptatibus dolorum impedit rem nisi nulla. Assumenda et quas eum vel aut ipsa vero a. Perspiciatis pariatur vel accusamus dolorum ullam a. Quo est deserunt libero aut quia dolorem. Optio eius magni consequatur quia voluptatem tenetur autem. Est nobis deserunt omnis quia perspiciatis quis accusamus doloribus. Debitis quibusdam cumque quidem. Atque inventore incidunt id nihil a neque. Nostrum nam ea ex. Id enim libero sit molestias. Praesentium voluptate temporibus voluptatem voluptatibus corrupti distinctio consequatur molestiae. Ad voluptas nisi voluptatem ratione quos distinctio libero et. Impedit expedita reiciendis id eveniet explicabo corporis. Consectetur consequatur ipsam delectus illo nam eligendi veritatis. Aperiam sequi quidem quia nihil distinctio tempore exercitationem. Qui quod et est sint nihil odit nisi. Odio architecto porro temporibus rerum nulla autem minima. Ut minus temporibus repellendus impedit. Adipisci qui inventore voluptate. Atque sed sint numquam molestiae. Consequatur commodi et excepturi quas eum. Molestias a provident in consequuntur cumque. Cumque consequuntur nobis asperiores possimus aut. Ratione soluta ea illo in dolorem soluta. Minus quis nobis porro non expedita. Aspernatur quaerat atque sint. Facere voluptas sint illo aut tempore veritatis. Neque facere et similique vitae consequatur dicta ullam porro. Minima rem tempora quae illo sit. Tempora molestias officia quos quam molestiae. Officia porro quia quasi facilis optio itaque. Excepturi voluptatibus est eaque. Illum aliquam nihil optio tempora qui. Aut earum nisi fuga saepe adipisci. Autem laboriosam velit voluptatibus necessitatibus nihil fugiat. Corrupti quaerat ea pariatur qui nulla. Quo praesentium quia quia dolorum odio voluptas ut. Laboriosam voluptas voluptatum magnam natus eos iste.','rem','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(11,'quia','1654587065.jpg','Quisquam assumenda culpa et reiciendis fugiat. Necessitatibus et non voluptatibus dolores. Ut distinctio iste consectetur iure illum non fuga est. Eos ea architecto itaque quod et. Quia odit eveniet explicabo eius. Ratione qui dolores maxime corrupti sed placeat veritatis dolorum. Labore in enim ullam assumenda dolorem sit illum. Mollitia nulla assumenda ab eveniet hic vero. Nihil quam maiores doloribus eum sequi quaerat. Sint tenetur et sed laudantium. Qui provident qui maiores perferendis sint repellat. Earum voluptatibus laudantium hic optio. Commodi illum quo quaerat atque. Molestiae laboriosam id velit est veniam sunt. Ipsam ipsam commodi voluptatem deserunt molestias accusamus. Quos neque laudantium nihil fugiat est et optio. Vel praesentium voluptate adipisci doloribus. Voluptatum vel delectus voluptas consequuntur. Vero laboriosam aut est et excepturi. Itaque eveniet aut voluptas tempore veritatis. Laboriosam dolore voluptatem ab porro sequi. Quae sint beatae in. Cum consequuntur aut sunt. Accusamus et labore autem illum aut odit qui. Porro vero iusto deserunt itaque et eos. Mollitia dignissimos sint delectus autem beatae. Odit ut quis quas. Corrupti molestias rerum et. Et vel deleniti inventore esse officiis debitis. Id quo fugiat omnis voluptatem nisi recusandae est. Quia iusto id vel doloribus omnis rerum animi error. Minus est et dicta illo sint aliquid nemo provident. Non nesciunt harum rerum quia. Eaque itaque quis dolores voluptatem quod. Voluptatem dolorum aut hic sapiente nulla consequuntur quia delectus. Accusamus necessitatibus quidem voluptatem soluta quo. Sunt tenetur tenetur voluptatem placeat. Blanditiis id blanditiis nulla consequuntur. Et sit est omnis qui. Ab est omnis est et repudiandae illum.','ex','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(12,'impedit','1654587065.jpg','Ut temporibus non officia similique facere. Officiis vel error distinctio qui numquam nihil nihil. Inventore possimus aut omnis corporis porro cupiditate quod. Molestiae repudiandae neque omnis necessitatibus. Sapiente quos provident sint. Nobis repellendus soluta odit ea ab. Beatae labore voluptatem consequatur est occaecati. A consequatur consectetur consectetur deserunt. Modi unde neque et temporibus. Et officiis ab possimus eum facere aspernatur temporibus. Non dolore numquam qui qui perspiciatis aut aliquid. Sit et id voluptatum fuga ipsum autem ut. Minima perferendis earum a libero odit. Nobis iste est est animi ipsum non facilis. Ea earum natus accusantium dolores. Nemo asperiores aut facere officiis architecto. Tempora molestias eum id saepe labore rem dolor. Id qui in laborum sed quasi consequatur. Voluptas aut aliquam mollitia qui quibusdam eum doloremque. Quod nihil quae itaque omnis repellendus dolores debitis. Facere quos nulla optio. Expedita eius sint corrupti eius impedit sed. Illo quis recusandae molestias laboriosam. Molestiae nihil quo quo dicta. Quae quis cupiditate laboriosam quidem. Repellendus similique fuga et odio. Magni et expedita culpa non dolorum incidunt. Earum quam repellat aut quis laboriosam explicabo saepe. Eligendi labore consectetur quam tempora consequatur omnis. Recusandae atque eligendi labore voluptas aspernatur placeat assumenda et. Cumque totam fugiat et nesciunt qui. Id et optio soluta placeat quibusdam enim facere. Placeat at neque libero possimus aut expedita. Illo consectetur voluptatibus impedit hic tempora et. Eligendi sunt qui atque minima molestiae corporis voluptatem. Et facere voluptate perspiciatis voluptas fugiat non eveniet. Iste sit quis aut voluptatum non aut et asperiores. Exercitationem ipsum velit quisquam explicabo commodi. Consequatur quam numquam eveniet accusantium est. Et qui vel consequatur.','provident','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(13,'soluta','1654587065.jpg','Sit sed est pariatur aut. Non illo eius enim reprehenderit itaque. Sed velit praesentium corrupti rerum. Saepe laboriosam quisquam eum non adipisci. Aperiam voluptatum expedita voluptatem illo optio sunt saepe minus. Cumque voluptas sit esse dolor. Numquam rem officia et. Et aspernatur voluptatem provident dolores vero voluptatum animi. Non non sunt nesciunt excepturi. Distinctio eius quis aut laudantium sequi ab possimus. Perspiciatis sint eveniet blanditiis similique. Voluptate placeat quia impedit enim ut beatae. Omnis illo earum ut maxime. Dicta qui impedit veniam veritatis. Porro et maxime at eligendi sit ad sunt est. Quia hic quis pariatur sit. Aut occaecati quia quod sequi et enim. Rem consequatur illo maiores corrupti omnis. Omnis voluptas debitis vel fugit rerum animi. Voluptas recusandae recusandae suscipit mollitia aut consequatur et. Aut vitae ipsam sed excepturi culpa velit officiis consequatur. Quo est atque et dignissimos modi praesentium voluptatem possimus. Laboriosam distinctio hic dolorem totam atque voluptates. Debitis est blanditiis et quae optio quasi nobis. Minus ut suscipit veritatis ducimus minus iste ab. Expedita fugit est culpa omnis et eius recusandae quo. Qui fugit pariatur aliquam occaecati quasi iure. Sit vel voluptatem aut. Necessitatibus hic incidunt sunt ea et est voluptate. At deleniti ut minima. Dolorem dolores et aut voluptatem optio. Ea modi ex ut rerum numquam. Et nisi dolor quod eos. Modi illo sed est. Quas et doloribus ut consequatur. Et officiis quos delectus odio. Unde autem quo delectus facere numquam quidem. Nihil ut exercitationem assumenda eligendi. Qui omnis delectus qui pariatur minima magnam temporibus. Beatae quis nobis ex repellendus.','veniam','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(14,'doloribus','1654587065.jpg','Recusandae distinctio omnis est saepe et ut ducimus sunt. Vel libero consequatur consectetur deleniti. Dignissimos neque sapiente harum. Corporis perspiciatis hic repellat est. Magni iusto consequatur expedita laborum sint. Corporis vitae cumque quis ducimus sequi. Aliquid dignissimos vero sed corporis earum et iusto. Vero aliquam totam ab voluptatibus reprehenderit magnam eveniet. Velit quaerat provident eius consequuntur voluptates eum. Id consequatur aperiam quis accusantium. Pariatur rem dicta non aut velit incidunt porro. Ipsa qui voluptas corrupti minus dolorum. Deleniti doloribus occaecati sed. Doloremque rem aut et aliquid qui porro ut quam. Voluptatem dolores in iusto itaque quo minus voluptas. Delectus ut rem voluptas maxime consequatur ut tempora dolorem. Necessitatibus id molestiae voluptas rerum ut fugiat. Dolor sed rerum iure cupiditate ut est. Quo asperiores ut quisquam quo delectus. Consequatur ut natus et dolor praesentium. Neque ut enim quisquam voluptas. Quia quas dolorem perferendis maxime. Excepturi aut aut ullam. Occaecati veritatis autem est omnis illo mollitia aut eaque. Voluptas natus aliquid ut. Quia aperiam id fugit nulla. Velit ut voluptate facere dolor. Commodi quasi distinctio tempora ut. Odio eos natus ducimus velit ut corporis officiis eaque. Iste alias eum in asperiores eius facere est. Eaque ut sit rerum voluptas asperiores eligendi. Autem temporibus dolores aspernatur. Vel officiis itaque et quia accusamus provident ad odit. Fuga aliquid excepturi nihil. Ut molestias unde ea in aut veritatis. Nostrum numquam eos nam mollitia consequatur quaerat. Hic modi eligendi esse officia labore est quod. Eligendi odit aperiam hic saepe blanditiis consectetur. Dolorem iste nihil quo qui recusandae eum sit. Nostrum distinctio aut inventore temporibus fugit neque officia dolore.','quo','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(15,'necessitatibus','1654587065.jpg','Sunt sint doloremque est porro et at nostrum. Illum fugiat et ut sed eligendi architecto ut. Possimus beatae praesentium architecto ut sapiente sit perferendis. Doloribus ab dolorem quidem fuga. Molestiae et voluptatem nemo asperiores ea atque. Illum eius hic aut ut aut possimus voluptatem. Similique doloremque consequatur consequuntur quidem exercitationem sint molestiae quod. Explicabo voluptas iusto dolorem excepturi reprehenderit aut et. Esse dolor eum sit ea natus ipsam sint. Itaque vero laudantium non autem velit et. Non ea quia qui accusamus aut. Veniam similique veritatis recusandae dolores aut voluptas. Qui et quia laudantium labore rerum. Ut est animi impedit nesciunt minus. Iure a qui impedit consectetur totam harum. Et similique autem quo voluptates voluptatem tempora. Dolores nihil pariatur consequatur hic aliquid id. Laboriosam omnis natus laborum autem eos rerum porro. Ullam iusto incidunt veniam magnam impedit ad similique. Et nihil eum in voluptatibus ea accusamus. Omnis corrupti repellat et nulla nulla. Facere in et qui porro. Placeat ab rerum omnis eligendi quaerat aut consequatur. Ut blanditiis et nihil mollitia rem deleniti. Ut facere fugiat id voluptas eligendi debitis in aut. Ullam est dolore esse et doloribus reiciendis ut. Perferendis quia et amet est voluptatibus. Quidem provident officia explicabo fugiat. Ad id quia amet aliquid sit. Dignissimos voluptatum dolores enim veritatis reiciendis voluptate ducimus sit. Quae id possimus sed id. Dignissimos et qui delectus sed rem. Similique dolores non laudantium ipsa optio repudiandae sit. Quibusdam labore quos occaecati ducimus non maiores sed. Magnam est hic ut odio suscipit odit aut. Earum earum aliquid minima enim voluptatem facilis in aut. Et non inventore dolores perferendis quidem est optio. Aspernatur illo ex voluptas. Maxime reiciendis ab cum dolorem nisi. Sunt incidunt et pariatur dolore rem delectus animi molestiae.','quis','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL);

/*Table structure for table `contactus` */

DROP TABLE IF EXISTS `contactus`;

CREATE TABLE `contactus` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_replied` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `contactus` */

/*Table structure for table `failed_jobs` */

DROP TABLE IF EXISTS `failed_jobs`;

CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `failed_jobs` */

/*Table structure for table `migrations` */

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `migrations` */

insert  into `migrations`(`id`,`migration`,`batch`) values 
(23,'2014_10_12_000000_create_users_table',1),
(24,'2014_10_12_100000_create_password_resets_table',1),
(25,'2019_08_19_000000_create_failed_jobs_table',1),
(26,'2019_12_14_000001_create_personal_access_tokens_table',1),
(27,'2022_05_30_031524_create_about_table',1),
(28,'2022_05_30_031614_create_blogs_table',1),
(29,'2022_05_30_031749_create_contactus_table',1),
(30,'2022_05_30_031807_create_pages_table',1),
(31,'2022_05_30_031823_create_services_table',1),
(32,'2022_05_30_031835_create_slider_table',1),
(33,'2022_05_30_034322_create_settings_table',1);

/*Table structure for table `pages` */

DROP TABLE IF EXISTS `pages`;

CREATE TABLE `pages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `pages` */

insert  into `pages`(`id`,`title`,`image`,`description`,`slug`,`type`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'Terms and Condition',NULL,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur','terms','page','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(2,'Privacy',NULL,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur','privacy','page','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL);

/*Table structure for table `password_resets` */

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `password_resets` */

/*Table structure for table `personal_access_tokens` */

DROP TABLE IF EXISTS `personal_access_tokens`;

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `personal_access_tokens` */

/*Table structure for table `services` */

DROP TABLE IF EXISTS `services`;

CREATE TABLE `services` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `services` */

insert  into `services`(`id`,`title`,`image`,`description`,`slug`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'at repudiandae','1654587175.png','Vero et in facere exercitationem. Velit quos nihil adipisci optio expedita. Quas ut facere sunt nostrum omnis nemo hic. Voluptates eos illo vel aperiam. Sint et accusantium aperiam nihil. Repellat dignissimos sed consectetur velit tenetur et rerum. Quos iusto illum quidem. Aspernatur non assumenda itaque laboriosam. Culpa cupiditate perferendis ullam a. Praesentium consequatur omnis ut nisi cumque. Nulla facilis ad voluptatem qui blanditiis. Quis architecto voluptatem vel soluta. Distinctio architecto similique deleniti placeat enim minima. Tempora aut ducimus labore deserunt eveniet. Veniam rem optio facilis sunt. Soluta magni aut voluptatum hic numquam. Et numquam non dignissimos dolores molestiae eum. Cumque odit saepe est tempora minima architecto iure quam. Quo fuga dicta omnis nihil commodi neque sunt nam. Ut repellat et quis at minima. Perferendis cum quo id et pariatur nulla modi. Nisi esse nisi ut. Vel esse voluptatem rerum. Ullam vero optio eveniet distinctio. Earum est eos est vel accusamus odio nulla.','cumque-sunt-temporibus','2022-06-07 07:29:25','2022-06-07 07:32:55',NULL),
(2,'eum cumque','1654587175.png','Possimus incidunt est consequuntur laboriosam sit accusamus. Praesentium sint et praesentium. Quasi quos enim nisi. Quia quo qui dolores animi nobis ut a. Non iste dolore nam voluptas. Libero praesentium quae vero tempore repudiandae consectetur consequatur cum. Nemo fugit sed tempore temporibus tempore dolorem. At laboriosam qui itaque voluptas. Quo nobis similique perferendis est. Quia soluta vel esse deleniti. Quidem saepe ipsa libero ut quaerat. Veritatis fugiat facere et dolor rem. Incidunt ad nobis corporis vero iusto tempore et. Explicabo minima itaque omnis ad maiores. Non quaerat molestiae aut nisi quam voluptatem. Repellendus qui et totam. In optio cumque perspiciatis mollitia. Porro autem incidunt autem corrupti quos placeat vero. Qui dicta pariatur asperiores iure sed tempora. Quis voluptas ipsa reprehenderit aspernatur sed earum et. Omnis autem velit quia voluptas voluptatem. Sed est rerum perspiciatis ex quos doloribus et. Odio recusandae quam cum est a sequi nesciunt enim. Maxime magnam odit ut laudantium. Rem eum ex tempore eum.','repudiandae-placeat-dignissimos','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(3,'vitae eaque','1654587175.png','Eos rerum et sunt fuga reiciendis fuga doloribus. Repellendus qui omnis labore eveniet occaecati quasi ipsa. Aut voluptatem numquam velit veniam est dolorum quod. Aspernatur voluptatem veniam consequatur perspiciatis velit tempora cum. Rerum similique sed dolores tenetur eum sit qui. Error libero sed nostrum dolore nesciunt ipsum. Qui natus atque nam. Autem aut aspernatur vero dicta est asperiores. Et omnis odit iste blanditiis. Ut eaque saepe doloribus vel atque. Qui alias ex qui debitis et alias eos. Pariatur est sit consequatur molestiae. Ut sequi consequatur quo laudantium voluptatem. Ex quisquam odit in iure et. Magnam dignissimos facilis doloribus nesciunt consequatur enim rem. Dolores doloribus velit delectus. Ut qui ratione accusamus tempora. Amet voluptas est illum sunt eaque. Tempora in molestias minus quo mollitia rem esse. Et voluptatem esse rerum itaque eveniet maiores. Voluptas maxime perspiciatis et consequatur asperiores. Dolore ipsam vero autem neque. Dolor quod et et quia sunt. Officiis sint dolor autem neque est. Ut rerum ratione autem dolor non.','voluptas-deserunt-ipsam','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(4,'itaque eveniet','1654587175.png','Architecto corporis quae aut eligendi accusamus modi. Vero voluptate optio voluptatum nobis nostrum libero id ut. Eum earum voluptas dolore. Veritatis et cumque excepturi autem. Veniam ad quis voluptatibus. Eos qui sed eos eaque corrupti non adipisci sit. Enim at hic excepturi corrupti quo et dolorem ut. Et qui id natus neque. Corrupti rerum aut sint. Eveniet ad repellendus delectus rem necessitatibus. Labore esse non velit itaque et enim earum. Laudantium optio perferendis qui impedit sit. Ipsam incidunt est soluta autem. Iure velit inventore repellendus quibusdam culpa. Sit est omnis inventore maxime consequatur. Sed cum facere nisi quis earum quia. Debitis exercitationem asperiores corrupti libero quo dolorem. Esse pariatur ullam cupiditate ad qui eligendi sapiente. Quibusdam debitis velit vel velit cum voluptas illum. Ratione iure qui distinctio aut occaecati consequatur rem. Consequatur aut optio ad nihil. Magni dolore veniam ab tenetur culpa. Voluptates et tenetur itaque ut sapiente culpa qui sit. Reiciendis repellendus consequatur ipsam eius consectetur eveniet. Necessitatibus tempora occaecati et at molestiae fugit.','maiores-aut-at','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(5,'nisi sunt','1654587175.png','Et repellat molestias eveniet doloribus qui occaecati eaque. Ipsum voluptatibus aut beatae voluptatibus facilis ut fuga. Impedit nisi eum asperiores quos earum et. Quaerat quisquam est dolor aliquid. Excepturi corporis cumque voluptatem aliquid modi sunt. Quisquam aliquid optio provident dolores quam possimus sit repudiandae. Sit blanditiis laudantium voluptatem recusandae. Quisquam voluptas saepe nisi rerum. Perferendis distinctio sit voluptates voluptatum repellendus minus voluptas quidem. Ipsam quaerat sed id id nobis aut. Enim voluptas labore temporibus sit possimus quae ab. Ipsa consequuntur qui aliquam voluptatem ab quas. Ullam iure consectetur qui libero optio sit adipisci. Libero repudiandae voluptas quasi beatae harum. Fugit rem qui omnis sunt. Placeat nam et dolor occaecati incidunt animi. Sunt sit deleniti dolore sunt non quod. Qui nostrum nisi officiis culpa doloribus. Ratione placeat quo alias voluptatem eligendi. Reprehenderit facilis rerum eius aliquam. Ut voluptatum sit impedit dolor. Optio nemo vitae in consequatur et molestiae repellat. Magnam eos perspiciatis hic quis magni quae omnis. Quibusdam natus soluta natus eum qui eum consequatur possimus. Asperiores placeat neque deleniti dolor.','quod-sequi-ut','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(6,'recusandae saepe','1654587175.png','Eveniet quae architecto voluptas quia. Autem omnis ex veritatis eveniet quia dignissimos ad. Optio dicta quos nobis et itaque quod delectus at. Iste aut eligendi mollitia in iusto qui. Neque et accusamus nihil aspernatur. Excepturi quod dolor cumque tempore et nulla alias. Qui perspiciatis cupiditate neque quo alias. Quasi adipisci sit enim aut laborum eos atque. Id nisi nobis earum asperiores corporis et rerum dolor. Consequatur quisquam aut sed fugit natus doloribus. Ut officia voluptas est. Mollitia repellat amet quia velit id aspernatur possimus porro. Quisquam minima iusto saepe autem unde ea repellendus. Ut harum earum similique hic totam et distinctio. Ducimus repellendus asperiores vero maxime. Sed sed eaque sint sint inventore. Rem quo iure et dolor asperiores. Et minus ad quo vero. Aut consequatur inventore omnis voluptatem commodi illum doloremque enim. Omnis vel corporis molestiae dolores maiores. Odio reprehenderit ex est itaque. Illum dolor voluptatem sequi id molestias illum ipsum laborum. Velit ea nesciunt ea blanditiis. Occaecati accusantium ut molestiae est. Sint omnis praesentium itaque nihil.','dolores-molestiae-nostrum','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(7,'et eos','1654587175.png','Illo est consequatur nihil minus reprehenderit consequatur voluptas. Distinctio distinctio omnis dicta reiciendis eum accusamus. Perferendis voluptatem atque ipsa facere quidem sed. Sed quisquam aperiam qui. Qui rerum et perferendis quasi eum ratione. Blanditiis porro consequatur in libero temporibus non ea. Quis facilis facere enim voluptatem eos. Ipsa rerum ut enim. Quo eveniet sequi qui et doloremque unde ipsum. Itaque consequuntur et quia id. Voluptate delectus nesciunt pariatur voluptatem nostrum cupiditate. Fugiat ut necessitatibus rerum enim voluptas eos quia repellat. Omnis rerum omnis vero deleniti quaerat est. Provident repudiandae adipisci libero hic vel explicabo molestiae. A et ut excepturi vitae quod eos fugit. Qui nemo quo pariatur aut possimus id rerum. Sed consequatur eum corrupti suscipit qui explicabo. Nulla minima omnis sed ea. Laudantium facilis culpa rerum tempora magni assumenda. Qui molestias sunt nihil accusamus molestias ad voluptatem. Laborum corrupti qui asperiores vel soluta qui velit. Repellat eius qui rerum sint tenetur. Porro quae ad qui dolorem quaerat suscipit. Est ut et iure repudiandae eos veniam commodi at. Quia ex nihil ex eum quia aliquid saepe quasi.','consequatur-rerum-illo','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(8,'architecto sequi','1654587175.png','Sit neque ipsum sapiente expedita quaerat eos. Voluptatem repudiandae a et asperiores voluptas voluptas nemo. Recusandae accusamus quisquam officia. Ipsa ea totam ea. Quia qui minus voluptatibus alias qui. Iure debitis a in possimus. Provident dicta harum quae qui facilis. Sunt et voluptates necessitatibus. Iure sed illo ut et non excepturi. Ducimus rerum officia impedit rerum. Atque libero aut excepturi accusantium perspiciatis distinctio. Nesciunt cupiditate quis aut quaerat dolorem. Quo laboriosam voluptate est excepturi sed pariatur. Dolor magnam earum sed voluptates sunt. Velit doloribus ut dolorum molestiae. Iusto quisquam qui tempora. Dolor velit ut dolorum hic. Magnam neque recusandae perspiciatis est. Adipisci adipisci adipisci voluptas illo qui dicta enim. Eos adipisci et sed nisi accusantium maiores. Non sint aspernatur sequi ea reprehenderit delectus. Eius porro quaerat omnis quam quisquam quasi quos. Ut impedit exercitationem maiores explicabo illo nulla quis est. Illum adipisci quisquam et. Sed quidem cupiditate modi sit et.','tenetur-earum-et','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(9,'qui qui','1654587175.png','Eos accusamus voluptatem dolor rerum perferendis. Expedita et ipsum totam dolorum explicabo est. Nulla voluptates magni repellendus voluptate et iure. Dolorem voluptatem explicabo nisi et ut. Dolor distinctio quas impedit ut nemo voluptatem ad. Tempora omnis repellendus temporibus architecto quia quia. Inventore aspernatur et optio harum. Quia ut velit temporibus sed quibusdam qui quidem laboriosam. Fuga qui quae expedita. Recusandae est sit eos ea a cumque sit. Vero provident sed praesentium quo quod. Sunt voluptas quasi eum excepturi ipsum. Nisi cumque velit molestias autem qui eos. Nobis at blanditiis laboriosam quas totam. Ad quos officia cumque. Possimus debitis iusto optio. Odio velit eligendi quia ut libero eaque. Eligendi quis et aut magni autem pariatur. Omnis qui minus perspiciatis doloremque. Voluptatibus aut beatae recusandae asperiores. Consequatur esse voluptate quibusdam impedit vel perspiciatis quia. Quia neque dolorem voluptatum voluptatem voluptatem. Est ullam temporibus sed. Ducimus ut perferendis blanditiis at sint. At facilis magnam sint.','iste-unde-consequatur','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(10,'magni illum','1654587175.png','Pariatur cum et illum animi voluptas consectetur necessitatibus. Est necessitatibus illum vitae optio veniam. Quis et ea beatae. Corrupti ut et cum accusantium sunt omnis ipsam. Est nihil sed non vel voluptatem nisi. Vel et eos voluptatem suscipit fugiat ut laborum. Quia aperiam officia voluptas et quia. Quisquam doloremque laborum alias ex beatae aliquam at. Sunt natus magni optio dicta in id in. Enim dolores aut aliquam aut. Aut velit et ducimus ex. Et voluptatum fugiat labore quasi temporibus vero quia. Est eaque eaque dolores ut. Quis quo deleniti qui quo temporibus et veniam. Eos tempore soluta suscipit iusto aut eos voluptatem beatae. Facere ut optio id officia consequuntur repellat esse. Velit eveniet a odit consequatur. Rerum ut aut consequatur laboriosam sint. Vel reiciendis voluptatem quisquam voluptates. Sit sunt rerum quod perspiciatis molestiae voluptas ipsa quos. Accusantium rerum mollitia dolor qui rerum dignissimos nesciunt. Voluptatem laboriosam ab ratione odit. Est tempore animi est nam vero aut autem. Sit laboriosam voluptas totam molestiae eius quibusdam autem. Inventore officia dolor eum qui commodi dolor tempore.','alias-dolores-delectus','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(11,'iusto expedita','1654587175.png','Quo quasi quidem fugiat mollitia. Impedit aut accusantium nam quia et ipsam est. Ut mollitia quia nam veniam qui exercitationem. Nihil omnis ratione adipisci similique in. Doloremque animi nobis at dolores repellat. Saepe voluptates quisquam atque et voluptatem id quisquam. Et nemo commodi nostrum impedit consequatur eos aut eligendi. Animi voluptatem exercitationem asperiores ratione quod nam. Eveniet voluptate ullam quae. Nesciunt ipsa aspernatur praesentium. Eaque neque culpa ipsum voluptatem vel ut. Est quisquam quisquam expedita fugiat eos. Soluta eos unde et voluptatem magni praesentium. Velit error fuga rerum optio fugit quae placeat. Est dolorem cupiditate qui sapiente. Soluta fugiat pariatur maxime velit et voluptas. Omnis accusamus consectetur qui consequuntur tempore quia. Id soluta enim et perspiciatis illo. Ullam sequi repellat vel architecto. Vel et nesciunt magnam doloremque dolor. Nobis hic ducimus sapiente enim nisi et adipisci. Cupiditate eum autem fuga. Tempore beatae et dolorum tempora consequatur quisquam. Molestiae laudantium libero delectus est placeat qui. Nulla quis ducimus ea distinctio sed consequatur.','nisi-nulla-et','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(12,'dolorem porro','1654587175.png','Inventore veniam at sunt magnam. Harum officiis qui dignissimos adipisci quo. Autem esse nihil veniam dicta vel reprehenderit magni. Ut praesentium aut et. Est consequuntur ut culpa aliquam quia. Vitae provident sit id corrupti. Dolores asperiores voluptatem natus fugit et et. Qui laudantium voluptas unde tempore voluptas explicabo. Perferendis illo accusamus at non. Et ducimus delectus labore. Nobis blanditiis quibusdam expedita unde. Maxime recusandae dolor illo occaecati perspiciatis maxime. Reiciendis deserunt facere sint quo placeat corrupti est. Illum incidunt reprehenderit ut laborum. Et impedit aliquid rem dolore. Est saepe autem earum corrupti quasi et voluptas. Culpa id vel et non sint est. Nesciunt omnis quia inventore quisquam reprehenderit. Occaecati atque iure eveniet. Vel soluta porro et voluptas. Voluptatem saepe sint maiores. Repellat nisi rerum ipsam error ratione aperiam soluta. Natus unde quidem aut sit necessitatibus voluptas. Omnis aut reiciendis similique doloribus. Reprehenderit voluptatem voluptatem cumque quia adipisci.','quo-est-est','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(13,'numquam incidunt','1654587175.png','Aut suscipit quam quisquam dolorem. Accusamus ratione illo odit dolores maiores quisquam facere et. Atque totam quod vitae fugit eos sed. Quam ut nobis voluptatem omnis consectetur. Aut sint aliquid quasi adipisci quas optio. Eveniet reiciendis repellendus a blanditiis neque omnis. Repellendus velit esse voluptatem et et explicabo. Et modi distinctio odio sed delectus. Quis aut hic voluptates molestiae magni. Omnis consequuntur vel ea sapiente reiciendis est sequi. Dolor eum rem quam alias cumque expedita. Ipsam similique sequi fuga autem ut ut iste. Consequatur eius excepturi soluta voluptates voluptates. Quia in tempore dolores vero. Rerum a similique ut ullam quas nobis. Recusandae aperiam at adipisci soluta nulla quis enim. Sint quidem libero ad veritatis sint qui voluptas. Eligendi magni molestiae quia. Porro eius dolore vel qui. Aut ex doloremque fugiat quia non voluptatibus. Officia ullam perferendis commodi labore sint. Iusto aut repudiandae tempora quo cum. Voluptatibus sed in et autem. Nam numquam impedit id atque et ducimus sequi. Sed odio et autem quo consequuntur repellendus impedit.','minima-distinctio-nemo','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(14,'quis praesentium','1654587175.png','Doloremque est ut voluptates aut. Aut itaque et quidem sed vel assumenda. Tempora et odio est laborum voluptates quia. Illum ad quaerat voluptas quia et et. Minima illum ut animi reiciendis deleniti. Ut vero omnis et ut quasi. Nisi repudiandae enim fugiat quia dignissimos nisi voluptas. Occaecati in in libero itaque est. Modi hic culpa qui et assumenda. Cupiditate cupiditate ratione error pariatur excepturi ratione ullam. Harum quo non quo commodi aut recusandae non. Deleniti voluptate incidunt veritatis. Sit voluptate nisi voluptatem repudiandae quia. Ipsam velit earum distinctio sed eos dolorem qui. Consequatur pariatur dolores sed non sit. Labore quidem at vel non voluptates. Repellendus laborum quo doloremque et eius. Eos consequatur quia non possimus voluptas ut similique. Quo aut aut in omnis in. Alias voluptatem aliquam nostrum voluptatem dolorum. Dolor et officiis sed sit iusto vitae quasi aut. Omnis provident minima molestiae quia. Autem tempora totam optio sunt. Commodi commodi error aut placeat alias molestias doloribus culpa. Mollitia modi nihil et unde similique fugiat.','et-officiis-qui','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(15,'quia odit','1654587175.png','Totam corrupti cumque minus vitae veniam molestias. Molestiae illo dolor sed laborum voluptate nisi nulla omnis. Deleniti deleniti ab aut nesciunt quos non omnis. Qui molestiae voluptas repellendus. Labore sed quis dolorum delectus nesciunt vitae. Impedit nulla quis reprehenderit ducimus rerum quae. Blanditiis quidem voluptatum quis quia officia explicabo odit. Dolores cupiditate maiores commodi omnis qui voluptatum. Eaque sit officiis aut modi consequatur aliquam. Reiciendis aut vel aliquam distinctio in. Occaecati veritatis est occaecati nihil ex. Quae autem soluta velit aut et autem. Similique deserunt ipsam quis autem optio ipsa. Earum velit et voluptatum asperiores. Voluptates ullam consequatur aut odit. Cumque repellat rerum saepe impedit est. Adipisci et impedit repellat qui. Dolorem ad distinctio eos aut. Dolorem rerum ipsa expedita sapiente. Praesentium qui accusamus sed nostrum nulla. Aliquid illo velit sit quas dignissimos aut vel aperiam. Est quia facere consequatur corrupti pariatur molestiae rerum. Consectetur necessitatibus error ut similique neque. Aspernatur sapiente quidem doloremque quibusdam molestiae aut accusamus. Sit sed et perspiciatis dolorem expedita error.','beatae-eveniet-non','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL);

/*Table structure for table `settings` */

DROP TABLE IF EXISTS `settings`;

CREATE TABLE `settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `settings` */

insert  into `settings`(`id`,`title`,`image`,`link`,`type`,`created_at`,`updated_at`) values 
(1,'Facebook','1654587251.png','http://facebook.com','social','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(2,'Facebook','1654587251.png','http://facebook.com','social','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(4,'Facebook','1654587251.png','http://facebook.com','address','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(5,'Facebook','1654587251.png','http://facebook.com','address','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(6,'Facebook','1654587251.png','http://facebook.com','social','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(7,'Facebook','1654587251.png','http://facebook.com','address','2022-06-07 07:34:11','2022-06-07 07:34:11'),
(8,'Facebook','1654587251.png','http://facebook.com','social','2022-06-07 07:34:11','2022-06-07 07:34:11');

/*Table structure for table `slider` */

DROP TABLE IF EXISTS `slider`;

CREATE TABLE `slider` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `slider` */

insert  into `slider`(`id`,`title`,`description`,`slug`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'veniam sint','Ut praesentium esse perferendis a dolorem nemo earum aperiam. Sunt ut vel nulla veritatis minus ex.','enim-autem-assumenda','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(2,'molestiae culpa','In est autem voluptates pariatur atque. Dicta vel aspernatur nisi aut et nobis.','accusamus-maiores-odio','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL),
(3,'illo qui','Omnis sint cum at vel dolore possimus ut. In quibusdam sit rem tenetur repellendus consequatur.','et-voluptatem-maxime','2022-06-07 07:29:25','2022-06-07 07:29:25',NULL);

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`) values 
(1,'Adele Langosh IV','faustino07@example.com','2022-06-07 07:29:23','$2y$10$GHBBu8N0nvgScaWNWbsFu.F6nTHw5JMKW.QxLPI6s2kcJ2TfY40sy','CjIImomwXi','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(2,'Ms. Alva Hyatt','iziemann@example.com','2022-06-07 07:29:23','$2y$10$udTCEFbOORHr3/XDcZPoPONjfFi2euLIByljp5hm5J4Dlc6dNRrUa','CINQM3Czpm','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(3,'Violette Spencer','jolie88@example.org','2022-06-07 07:29:23','$2y$10$8Cr3jvofxx.lr2Vkbaud0uAyZl1GfIz3BGVvAMwcyO9MtDvtpsn3W','xBlq9wwpNt','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(4,'Mrs. Katelynn Reichel','nels73@example.net','2022-06-07 07:29:23','$2y$10$UHnM5tPfjo2q0/eCZiJX7u5pWBT5AC5jAVV5SEuZI2qtmRkjPnDp6','0QiMLAaeOS','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(5,'Jermey Haley','bennett26@example.com','2022-06-07 07:29:23','$2y$10$La0Xm0sIsLhkuXavXOdEtONxv9Ru1nJkzM2aPwGz9r.RBNUKIkHoi','HfGCLvuOIw','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(6,'Dr. Garth Denesik','glenna.hamill@example.net','2022-06-07 07:29:23','$2y$10$/hBNJaVqmxggUL3.4AQGZuUIlwpyrLQsN1ozL6cLsz5SX1b5bXnim','TyvtVX06QB','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(7,'Miss Marilyne Crona II','elouise.balistreri@example.com','2022-06-07 07:29:24','$2y$10$DMpA5BeG/w6SaUSfDEJ6hOdzSUsYnMrlyCj0r.3qnJDCBTqT.iAxC','Haw00rziDT','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(8,'Mr. Ronny Altenwerth PhD','osborne.becker@example.net','2022-06-07 07:29:24','$2y$10$bhTeTl7Q50sdWRity8UrBul8qv/M/wu7tOi4wpIYAE.3RSGAjzXO2','tZQ0kNatDY','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(9,'Willa Gaylord PhD','denis.heller@example.com','2022-06-07 07:29:24','$2y$10$HOBj3u8SpZNygdF.6.AgMefqlQLpuO84kg1eCbL0Aey4/wn2iSpRa','25huUXkXOx','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(10,'Dr. Zetta Strosin DDS','ferry.mathilde@example.org','2022-06-07 07:29:24','$2y$10$p.UB/ol0/ZOJrSI0TtxJ2.ykCynN8Qm3dXwzTT.qIXeRAXb9VaIri','vZskfcsc8E','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(11,'Zackery Koepp','beatty.ruben@example.net','2022-06-07 07:29:24','$2y$10$6G5sJqnoqpk5DsiB8xVPIu2JMb48wAhGReIXUBBvwpN.D.HTc7ao2','iMXkZ2LEL1','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(12,'Selmer Huels','cormier.cleora@example.org','2022-06-07 07:29:24','$2y$10$kDCK1dAUr/XIOCZ0lkpu.uH8kW2HX/0f.H50Javfd.7X0MtktT3Wq','MqkS34NaJm','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(13,'Nathan Von','jacky.mertz@example.net','2022-06-07 07:29:24','$2y$10$Z5naJ4FQH97c.eP5vsIt2eUqQD1YJ1kYnLmnKR3uMyGQHkchrzMXu','IlIC9njjjQ','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(14,'Chris Christiansen','dietrich.florida@example.net','2022-06-07 07:29:24','$2y$10$790KFZcg/iQcx61SsTCwFezwDTV.C8GtlYx6.OndN0QkWwalh94W2','KSOoXTt8ng','2022-06-07 07:29:25','2022-06-07 07:29:25'),
(15,'Xzavier Predovic','barton.sammy@example.net','2022-06-07 07:29:24','$2y$10$hcu44TIZxW5CZ5w/uuoi8OnJ0CJ17ZNFveLV6npP.VbcuI.lQvodO','tsTrTz38LK','2022-06-07 07:29:25','2022-06-07 07:29:25');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
